/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SentimentRouteImport } from './routes/sentiment'
import { Route as ReengageRouteImport } from './routes/reengage'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'

const SentimentRoute = SentimentRouteImport.update({
  id: '/sentiment',
  path: '/sentiment',
  getParentRoute: () => rootRouteImport,
} as any)
const ReengageRoute = ReengageRouteImport.update({
  id: '/reengage',
  path: '/reengage',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/customers': typeof CustomersRoute
  '/generate': typeof GenerateRoute
  '/messages': typeof MessagesRoute
  '/reengage': typeof ReengageRoute
  '/sentiment': typeof SentimentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/customers': typeof CustomersRoute
  '/generate': typeof GenerateRoute
  '/messages': typeof MessagesRoute
  '/reengage': typeof ReengageRoute
  '/sentiment': typeof SentimentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/customers': typeof CustomersRoute
  '/generate': typeof GenerateRoute
  '/messages': typeof MessagesRoute
  '/reengage': typeof ReengageRoute
  '/sentiment': typeof SentimentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/customers'
    | '/generate'
    | '/messages'
    | '/reengage'
    | '/sentiment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/customers'
    | '/generate'
    | '/messages'
    | '/reengage'
    | '/sentiment'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/customers'
    | '/generate'
    | '/messages'
    | '/reengage'
    | '/sentiment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  CustomersRoute: typeof CustomersRoute
  GenerateRoute: typeof GenerateRoute
  MessagesRoute: typeof MessagesRoute
  ReengageRoute: typeof ReengageRoute
  SentimentRoute: typeof SentimentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sentiment': {
      id: '/sentiment'
      path: '/sentiment'
      fullPath: '/sentiment'
      preLoaderRoute: typeof SentimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reengage': {
      id: '/reengage'
      path: '/reengage'
      fullPath: '/reengage'
      preLoaderRoute: typeof ReengageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  CustomersRoute: CustomersRoute,
  GenerateRoute: GenerateRoute,
  MessagesRoute: MessagesRoute,
  ReengageRoute: ReengageRoute,
  SentimentRoute: SentimentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
